
import Head from 'next/head'
import bgimage from '../image/bg.jpg'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import AboutMe from '../components/AboutMe';
import WorkExperience from '../components/WorkExperience';
import Education from '../components/Education';
import Skills from '../components/Skills';
import MyWork from '../components/MyWork';
import Clint from '../components/Clint';
import BlogPost from '../components/BlogPost';
import Contact from '../components/Contact';


export default function Home() {
  const backgroundImage = {
    backgroundImage: `url("${bgimage}")`,
    backgroundSize: "cover",
    opacity: 0.9,
  };
  return (
    <div>
      <Head>
        <title>limon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <Navbar/>
     <Main/>
     <AboutMe/>
     <Education/>
     <WorkExperience/>
     <Skills/>
     <MyWork/>
     <Clint/>
     <BlogPost/>
     <Contact/>
    
    </div>
  )
}
